name: Bicycle_Frontend

on:
  push:
    branches:
      - main

jobs:
  myDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: For pick the repository
        uses: actions/checkout@v4
      - name: for connection
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{secrets.IP}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}

          script: |
            cd /home/mamta/bicyle_Frontend
            git pull origin main
            sudo npm i
            sudo npm run build
            cd dist/bicycle/
            sudo npm i pm2 -g
            pm2 start --name "Bicycle_Frontend" /usr/bin/http-server -- -p 4200 -d false
 
